databases:
  - name: planning_events
    plan: free
    databaseName: planning_events
    user: planning_events_user

services:
  - type: web
    plan: free
    name: planning_events
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn events.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: planning_events
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4 