databases:
  - name: planning-events
    plan: free
    databaseName: django_catcollector
    user: django_catcollector_user

services:
  - type: web
    plan: free
    name: planning-events
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn events.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_catcollector
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4 